import 'dart:async';                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                   
    import 'package:flutter_riverpod/flutter_riverpod.dart';                                                                                                                                                                                                                       
    import 'package:ride_together/features/map/domain/entities/map_mode.dart';                                                                                                                                                                                                     
    import 'package:ride_together/features/map/presentation/providers/map_mode_provider.dart';                                                                                                                                                                                     
    import 'package:ride_together/features/ride/domain/entities/ride.dart';                                                                                                                                                                                                        
    import 'package:ride_together/features/ride/domain/entities/ride_status.dart';                                                                                                                                                                                                 
    import 'package:ride_together/features/ride/presentation/providers/ride_repository_provider.dart';                                                                                                                                                                             
                                                                                                                                                                                                                                                                                   
    /// Controller handling UI action requests for Ride lifecycle (Create, Join, Leave, Status Update).                                                                                                                                                                            
    ///                                                                                                                                                                                                                                                                            
    /// SPRING BOOT ANALOGY:                                                                                                                                                                                                                                                       
    /// `@RestController` handling `@PostMapping` endpoints with async exception handling and UI state updates.                                                                                                                                                                    
    final rideControllerProvider =                                                                                                                                                                                                                                                 
        AsyncNotifierProvider<RideController, Ride?>(                                                                                                                                                                                                                              
      RideController.new,                                                                                                                                                                                                                                                          
    );

     class RideController extends AsyncNotifier<Ride?> {                                                                                                                                                                                                                            
      @override                                                                                                                                                                                                                                                                    
      Ride? build() {                                                                                                                                                                                                                                              
        // Initial build state is idle (null, no action currently running)                                                                                                                                                                                                         
        return null;                                                                                                                                                                                                                                                               
      }                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                   
      /// Creates a new ride as the leader and switches map mode to activeRide.                                                                                                                                                                                                    
      Future<Ride?> createRide({                                                                                                                                                                                                                                                   
        required String name,                                                                                                                                                                                                                                                      
        String? description,                                                                                                                                                                                                                                                       
        String? customJoinCode,                                                                                                                                                                                                                                                    
      }) async {                                                                                                                                                                                                                                                                   
        state = const AsyncLoading(); // Set UI state to Loading                                                                                                                                                                                                                   
        final repository = ref.read(rideRepositoryProvider);                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                   
        state = await AsyncValue.guard(() async {                                                                                                                                                                                                                                  
          final ride = await repository.createRide(                                                                                                                                                                                                                                
            name: name,                                                                                                                                                                                                                                                            
            description: description,                                                                                                                                                                                                                                              
            customJoinCode: customJoinCode,                                                                                                                                                                                                                                        
          );                                                                                                                                                                                                                                                                       
          // Update UI map mode to activeRide upon successful creation                                                                                                                                                                                                             
          ref.read(mapModeProvider.notifier).state = MapMode.activeRide;                                                                                                                                                                                                           
          return ride;                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                   
        return state.value;                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                   
      /// Joins an existing ride using its 6-character join code.                                                                                                                                                                                                                  
      Future<Ride?> joinRide(String joinCode) async {                                                                                                                                                                                                                              
        state = const AsyncLoading(); // Set UI state to Loading                                                                                                                                                                                                                   
        final repository = ref.read(rideRepositoryProvider);                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                   
        state = await AsyncValue.guard(() async {                                                                                                                                                                                                                                  
          final ride = await repository.joinRideByCode(joinCode);                                                                                                                                                                                                                  
          // Update UI map mode to activeRide upon successful join                                                                                                                                                                                                                 
          ref.read(mapModeProvider.notifier).state = MapMode.activeRide;                                                                                                                                                                                                           
          return ride;                                                                                                                                                                                                                                                             
        });                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                   
        return state.value;                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                   
      /// Updates the status of a ride (e.g. planned -> active -> completed).                                                                                                                                                                                                      
      Future<void> updateRideStatus({                                                                                                                                                                                                                                              
        required String rideId,                                                                                                                                                                                                                                                    
        required RideStatus status,                                                                                                                                                                                                                                                
      }) async {                                                                                                                                                                                                                                                                   
        state = const AsyncLoading();                                                                                                                                                                                                                                              
        final repository = ref.read(rideRepositoryProvider);                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                   
        state = await AsyncValue.guard(() async {                                                                                                                                                                                                                                  
          await repository.updateRideStatus(rideId: rideId, status: status);
          if (status == RideStatus.completed || status == RideStatus.cancelled) {
            ref.read(mapModeProvider.notifier).state = MapMode.idle;
          }
          return null;
        });
      }
  
      /// Leaves the current active ride and returns map mode to idle.
      Future<void> leaveRide(String rideId) async {
        state = const AsyncLoading();
        final repository = ref.read(rideRepositoryProvider);
  
        state = await AsyncValue.guard(() async {
          await repository.leaveRide(rideId);
          ref.read(mapModeProvider.notifier).state = MapMode.idle;
          return null;
        });
      }
    }